name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  simple_gradient_text: ^1.2.3
  flutter_gradient_colors: ^2.1.1
  animated_text_kit: ^4.2.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  rflutter_alert: ^2.0.4
  modal_progress_hud: ^0.1.3
  modal_progress_hud_nsn: ^0.2.1
  font_awesome_flutter: ^10.1.0
  awesome_dialog: ^2.2.1
  cool_alert: ^1.1.0
  firebase_storage: ^10.3.2
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
    - family: EduQLD
      fonts:
        - asset: assets/EduQLDBeginner-Regular.ttf
        - asset: assets/EduQLDBeginner-Medium.ttf
    - family: Gulzar
      fonts:
        - asset: assets/Gulzar-Regular.ttf
    - family: Lemonada
      fonts:
          - asset: assets/Lemonada-Light.ttf

